name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven
    - uses: s4u/maven-settings-action@v4.0.0
      with:
        sonatypeSnapshots: true
        apacheSnapshots: true
        servers: |
          [{
              "id": "ossrh",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
          }]        
    - name: Package and test generator
      run: mvn package -U -B
      working-directory: pom
    - name: Deploy generator
      run: mvn deploy -Dmaven.test.skip -B
      working-directory: pom
    - name: Package and test data
      run: mvn package -U -B
      working-directory: data
    - name: Deploy data
      run: mvn deploy -Dmaven.test.skip -B
      working-directory: data
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit: "**/target/surefire-reports/*.xml"
      
  sonar:
    name: Run Sonar analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        # Shallow clones should be disabled for a better relevancy of analysis
        fetch-depth: 0  
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - uses: s4u/maven-settings-action@v4.0.0
      with:
        sonatypeSnapshots: true
        apacheSnapshots: true
        servers: |
          [{
              "id": "ossrh",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
          }]        
    - name: Build and analyze generator
      env:
        # Needed to get PR information, if any
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B -P coverage verify sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_KEY }}
      working-directory: pom
    - name: Build and analyze data
      env:
        # Needed to get PR information, if any
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B -P coverage verify sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_KEY }}
      working-directory: data
