name: Update JRS snapshots

on:
  workflow_dispatch:
  schedule:
  - cron: '0 5 * * *'
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - uses: s4u/maven-settings-action@v2.7.0
      with:
        sonatypeSnapshots: true
        apacheSnapshots: true
        servers: |
          [{
              "id": "ossrh",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
          }]        
    - name: Update dependencies
      run: mvn -B versions:resolve-ranges versions:update-properties -Dincludes=com.jresearchsoft*:*,org.jresearch*:* -DallowSnapshots --builder singlethreaded
      working-directory: pom
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4    
      with:
        branch: dep-update
        commit-message: Update shapshot dependencies
        token: ${{ secrets.PAT }}
